[versions]
agp = "8.7.3"
kotlin = "2.0.20"
composeAndroid = "1.7.5"
composeMultiplatform = "1.7.1"
espresso = "3.6.1"
junit5 = "5.11.3"
kotlinxSerialization = "1.7.3"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.0" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version = "2.1.3" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.0" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.2.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
material-view = { module = "com.google.android.material:material", version = "1.12.0" }

androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.6.2" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.6.1" }
androidx-test-junit = { module = "androidx.test.ext:junit", version = "1.2.1" }
test-junit4 = { module = "junit:junit", version = "4.13.2" }
test-junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
test-junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "composeAndroid" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "composeAndroid" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "composeAndroid" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeAndroid" }
compose-material3 = { module = "androidx.compose.material3:material3", version = "1.3.1" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.9.3" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version = "2.8.4" }

compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "composeAndroid" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "composeAndroid" }

jetbrains-compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version = "2.8.0-alpha08" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version = "4.4.1" }
mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
versionCheck = { id = "com.github.ben-manes.versions", version = "0.51.0" }
bcv = "org.jetbrains.kotlinx.binary-compatibility-validator:0.16.3"

# KMM
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
